config/routes.rb
DailyReportSystem::Application.routes.draw do
  resources :users do
    member do
      get :activate,:gen_reports,:gen_reports_result,:gen_excel
    end
  end
  resources :activations, only: [:new, :create, :edit, :update]
  resources :group_users, only: [:new, :create, :destroy]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :reports, only: [:new, :create, :index] do
    member do
      get :serve
    end
  end
  resources :catalogs, only:[:new, :create]
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  email            :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  password_digest  :string(255)
#  activation_token :string(255)
#  remember_token   :string(255)
#
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_one :activation, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one :group_user, dependent: :destroy
  has_one :group, dependent: :nullify, foreign_key: 'manager'
  before_save { email.downcase! }
  before_save :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+-.]+@framgia.com\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :update
  validates :password_confirmation, presence: true, on: :update
  validates :activation_token, presence: true, on: :update
  class << self
    def auto_generate_password
      (0..5).map { ('a'..'z').to_a[rand(26)] }.join
    end
    
    def activate(user)
      @user = user
      @activation = Activation.find_by_user_id(@user.id)
      Activation.update(@activation.id, activation_status: 'activated')
    end
  end
  
  def activated?
    self.activation.activation_status == 'activated'
  end
  
  def manage!(group)
    group.update_attribute('manager', self.id)
  end
  
  private
  
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter 'signed_in_user', only: [:edit, :update, :index, :create]
  before_filter 'correct_user',   only: [:edit, :update]
  def index
    @users = User.paginate(page: params['page'], per_page: 20)
  end

  def show
    if signed_in?
      @user = User.find(params['id'])
      @groups = Group.all
    else
      redirect_to root_path
    end
  end

  def new
    redirect_to root_path if signed_in?
    @user = User.new
  end

  def create
    @user = User.new(params['user'])
    @user.password = @user.password_confirmation = User.auto_generate_password
    @user.activation_token = Digest::MD5::hexdigest(@user.email.downcase)
    @act = Activation.new(user_id: @user.id, activation_status: 'inactivated')
    if @user.save && @act.save
      mail_activate(@user)
      flash.now['message'] = 'signup success, check mail for password'
      render 'sessions/new'
    else
      flash.now['error'] = 'signup failed'
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params['id'])
    if @user.update_attributes(params['user'])
      flash['success'] = 'Profile updated'
      sign_in @user
      redirect_to @user
    else
      render :edit
    end
  end

  def activate
    @user = User.find_by_activation_token(params['id'])
    if @user
      User.activate(@user)
      flash.now['message'] = 'activation success'
    else
      flash.now['message'] = 'activation failed'
    end
    render 'static_pages/home'
  end

  def gen_reports
    @user = current_user
    @members = @user.group.users
  end

  def gen_reports_result
    @user = current_user
    @members = @user.group.users
    @type = params['type']
    @id = params['user_id'].to_i
    if params['type'] && params['user_id']
      @reports = User.find(@id).reports
      render :gen_reports
    else
      render :gen_reports
    end
  end

  def gen_excel
    @type = params['type']
    @id = params['user_id'].to_i
    @reports = User.find(@id).reports
    tmp = Tempfile.new('writeexcel')
    workbook = WriteExcel.new(tmp.path)
    worksheet  = workbook.add_worksheet
    format = workbook.add_format
    format.set_text_wrap
    mergedformat = workbook.add_format(
      border: 6,
      valign: 'vcenter',
      align: 'center')
    worksheet.write(0, 0, @type)
    header = Hash.new
    mark_row = Hash.new
    col = 0
    Catalog.all.each do |v|
      worksheet.write(0, col + 1, v.name, format)
      header[v.id] = col + 1
      mark_row[v.id] = 0
      col += 1
    end
    maxrow = 0
    case @type
    when 'week'
      @wreports = @reports.group_by(&:week)
    when 'month'
      @wreports = @reports.group_by(&:month)
    when 'year'
      @wreports = @reports.group_by(&:year)
    end
    @wreports.each do |week, wreport|
      wrow = maxrow
      while wreport.count > 0
        r = wreport.first
        col = header[r.catalog_id]
        data = r.content
        unless r.file.blank?
          data << "\n file: http://localhost:3000/reports/#{r.id}/serve"
        end
        worksheet.write(mark_row[r.catalog_id] + 1, col, data, format)
        mark_row[r.catalog_id] += 1
        maxrow = mark_row[r.catalog_id] if mark_row[r.catalog_id] > maxrow
        wreport.delete(r)
      end
      Catalog.all.each do |v|
        mark_row[v.id] = maxrow
      end
      if wrow + 1 < maxrow
      worksheet.merge_range(wrow + 1, 0, maxrow, 0, week, mergedformat)
      else
      worksheet.write(wrow + 1, 0, week, mergedformat)
      end
    end
    workbook.close
    tmp.read
    send_file(tmp.path, filename: "user#{@id}_by#{@type}.xls")
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def mail_activate(user)
    UserMailer.welcome_email(user).deliver
    UserMailer.active_email(user).deliver
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options['size']
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_activated.html.erb
<div class="row activated">
    <%= form_for(@user.activation, remote: true) do |f| %>

    <div>
        <%= f.hidden_field :activation_status, value: "inactivated"%>
    </div>
    <div class="span1">
        <%= gravatar_for @user, size:40%>
    </div>
    <div class="span4">
        <%= link_to @user.name,@user%> | <%= @user.email%>
    </div>
    <div class="span2">
        created at <%= @user.created_at.to_date%>
    </div>
    <div class="span3">
        <%= f.submit "Active", class: "btn btn-success" %>
    </div>
    <div class="span2">
        <%= link_to "edit",@user,class:"btn"%>
    </div>
    <% end %>

</div>

app/views/users/_activation_form.html.erb
<div id="activation_form_<%= @user.id%>">
    <% if @user.activated? %>
    <%= render 'activated' %>
    <% else %>
    <%= render 'inactivated' %>
    <% end %>
</div>

app/views/users/_gen.html.erb
<div class="span2">
    <%= form_tag gen_reports_result_user_path(@user), method: :get do%>
    <div class="row-fluid">
        <div class="span9">
            <%= label_tag :type, "Generate type"%>
            <%= select_tag :type, options_for_select(["week","month","year"])%>
            <%= label_tag :user_id, "Select member"%>
            <%= select_tag :user_id, options_from_collection_for_select(@members,:id,:name), size: 5%>
            <%= submit_tag "generate"%>
        </div>
    </div>
    <% end %>
</div>

app/views/users/_gen_excel.html.erb
<div class="row-fluid">
    <div class="span3 offset2">
    <%= form_tag gen_excel_user_path(@user), method: :get do%>
    <%= hidden_field_tag :type, @type%>
    <%= hidden_field_tag :user_id, @id%>
    <%= submit_tag "generate excel"%>
    <% end %>
    </div>
</div>

app/views/users/_group_assign.html.erb
<div class="span8">
    <%= form_for GroupUser.new do |f| %>
    <div class="span5">
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.label :group_id,"select group"%>
        <%= f.collection_select :group_id, @groups, :id, :name %>
        <%= check_box_tag :manager %> Assign group manager?
        <%= f.submit "Submit", class: "btn btn-primary"%>
    </div>
    <%end%>
</div>

app/views/users/_inactivated.html.erb
<div class="row inactivated">
    <%= form_for(@user.activation, remote: true) do |f| %>

    <div>
        <%= f.hidden_field :activation_status, value: "activated"%>
    </div>
    <div class="span1">
        <%= gravatar_for @user, size:40%>
    </div>
    <div class="span4">
        <%= link_to @user.name, @user%> | <%= @user.email%>
    </div>
    <div class="span2">
        created at <%= @user.created_at.to_date%>
    </div>
    <div class="span3">
        <%= f.submit "Inactive", class: "btn btn-warning" %>
    </div>
    <div class="span2">
        <%= link_to "edit",@user,class:"btn"%>
    </div>
    <% end %>

</div>

app/views/users/_row.html.erb
<tr>
    <td><%= @val%></td>
    <% for @catalog_id in @catalog_ids do%>
    <td> <% for @r3 in @r2 do%>
    <% if @r3.catalog_id == @catalog_id %>
    <ul>
        <li>
            <%= @r3.content%>
            {Attach File
            <%unless @r3.file.blank? %>
            <%= link_to File.basename(@r3.file.path), serve_report_path(@r3)%>
            <%end%>}
        </li>
    </ul> <%else%>
    <%= " "%>
    <%end%>
    <% end %> </td>
    <% end %>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> <h1>Update your profile</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        <% end %>

        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails">change</a>
    </div>
</div>

app/views/users/gen_reports.html.erb
<div class="row-fluid">
    <%= render 'gen'%>
    <% if params[:type] and params[:user_id]%>
    <div class="row-fluid">
        <div class="span9">
            <% @catalog_ids = Catalog.find(:all,select: :id,order: :id).map{|c| c.id} %>
            <table class="table table-bordered">
                <thead>
                    <th><%= @type%></th>
                    <%Catalog.all.each do |v|%>
                    <th><%= v.name %></th>
                    <% end %>
                </thead>

                <tbody>
                    <% case @type%>
                    <% when "week"%>
                    <% @reports.group_by(&:week).each do |val,r2| %>
                    <% @val = val
                      @r2 = r2%>
                    <%= render 'row'%>
                    <% end %>
                    <% when "month"%>
                    <% @reports.group_by(&:month).each do |val,r2| %>
                    <% @val = val
                      @r2 = r2%>
                    <%= render 'row'%>
                    <% end %>
                    <% when "year"%>
                    <% @reports.group_by(&:year).each do |val,r2| %>
                    <% @val = val
                      @r2 = r2%>
                    <%= render 'row'%>
                    <% end %>
                    <% end%>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
    <%= render 'gen_excel'%>
</div>
<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %> <h1>All users</h1>

<ol class="users">
    <% @users.each do |user| %>
        <% @user = user %>
        <% unless is_admin?(user)%>
            <li>
                <%= render "activation_form" if admin?%>
            </li>
        <%end%>
    <% end %>
    <%= will_paginate %>
</ol>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %> <h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <%= @user.email%>
      <%= @user.activation.activation_status%>
    </section>
  </aside>
  <%if admin?%>
    <%= render 'group_assign'%>
  <% end %>
</div>