config/routes.rb
DailyReportSystem::Application.routes.draw do
  resources :users do
    member do
      get :activate,:gen_reports,:gen_reports_result,:gen_excel
    end
  end
  resources :activations, only: [:new, :create, :edit, :update]
  resources :group_users, only: [:new, :create, :destroy]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :reports, only: [:new, :create, :index] do
    member do
      get :serve
    end
  end
  resources :catalogs, only:[:new, :create]
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_admin.html.erb
<li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <%= link_to "Reports", new_catalog_path %>
        </li>
        <li>
            <%= link_to "Users", users_path%>
        </li>
    </ul>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "daily report system", root_path, id: "logo" %>
            <nav>
                <ul class="nav pull-right">
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <% if signed_in? %>
                        <%if session[:admin]%>
                            <%= render 'layouts/admin'%>
                        <%else%>
                            <%= render 'layouts/user'%>
                        <%end%>
                        <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to "Profile", current_user %>
                                </li>
                                <li>
                                    <%= link_to "Settings", edit_user_path(current_user) %>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Sign out", signout_path, method: "delete" %>
                                </li>
                            </ul>
                        </li>
                    <% else %>
                    <li>
                        <%= link_to "Sign in", signin_path %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_normal_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "daily report system", root_path, id: "logo" %>
            <nav>
                <ul class="nav pull-right">
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <% if signed_in? %>
                    <li id="fat-menu" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daily Report <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "New", new_report_path %>
                            </li>
                            <li>
                                <%= link_to "Show", reports_path%>
                            </li>
                        </ul>
                        
                    </li>
                    <li id="fat-menu" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Profile", current_user %>
                            </li>
                            <li>
                                <%= link_to "Settings", edit_user_path(current_user) %>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Sign out", signout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                    <% else %>
                    <li>
                        <%= link_to "Sign in", signin_path %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user.html.erb
<li id="fat-menu" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daily Report <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <%= link_to "New", new_report_path %>
        </li>
        <li>
            <%= link_to "Show", reports_path%>
        </li>
        <li>
            <%if current_user.group %>
                <%= link_to "Generate Reports", gen_reports_user_path(current_user)%>
            <% end %>
        </li>
    </ul>

</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header'%>
        <div class="container">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>